---
- hosts: leaf spine
  vars:
    ansible_user: admin
    ansible_ssh_pass: YourPaSsWoRd
  become: true
  gather_facts: false
  tasks:
  - name: Restore config_db
    copy: src=./configs/{{inventory_hostname}}/config_db.json dest=/etc/sonic/config_db.json
    notify: reload sonic config

  - name: Set eth[1-20] MTU to 9238
    shell: |
      for i in $(ip link | grep eth[1-20] | awk -F':' '{print $2}'); do
        ip link set mtu 9238 $i
      done
    args:
      executable: /bin/bash

  - name: Check for ebtables.filter
    stat: path=/etc/ebtables.filter
    register: ebtables_stat

  - name: Disable default ebtables DROP rules
    command: mv /etc/ebtables.filter /etc/ebtables.filter.disabled
    when: ebtables_stat.stat.exists
    notify: flush ebtables

  handlers:
  - name: reload sonic config
    shell: config reload -y

  - name: flush ebtables
    shell: ebtables -F

- hosts: leaf spine
  vars:
    ansible_user: admin
    ansible_ssh_pass: YourPaSsWoRd
  become: true
  gather_facts: false
  tasks:
  - name: copy mac_address_changer_script to target host 
    copy: src=./configs/{{inventory_hostname}}/set_mac_addresses.sh dest=/root/set_mac_addresses.sh
  
  - name: set mac addresses 
    command: bash /root/set_mac_addresses.sh
  
  - name: copy bgp_redistribute_connected_script to target host 
    copy: src=./configs/{{inventory_hostname}}/bgp_redistribute_connected.sh dest=/root/bgp_redistribute_connected.sh
  
  - name: BGP redistribute connected routes
    command: bash /root/bgp_redistribute_connected.sh
